---
- name: checker
  hosts: localhost
  gather_facts: no

  vars_prompt:

    - name: pv2_path
      prompt: enter absolute path to pantheon2.yml file
      private: no

  tasks:

  - name: print pv2_path
    assert: that="pv2_path.strip()"
    args:
      msg: "The pv2_path argument shouldn't be empty!"

  - debug:
        var: pv2_path

  - include_vars: "{{ pv2_path }}"

  - debug:
    vars:
      - assemblies
      - modules

  - name: match string and write abstract tag
    lineinfile:
      path: /home/levi/rhel-8-docs/enterprise/assemblies
      line: '[role="_abstract"]'
      insertafter: "^= .*"
      state: present
    with_items: "{{ assemblies.files }}"
